# throw_try_catch_2